#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export GOPATH=~/devel/gowork

# Z
. ~/tools/z/z.sh

# mvn
alias mci="mvn clean install -q"
alias mi="mvn install -q"
alias mcist="mvn clean install -Dtest.skip=true -q"
